name: Check Release Branch

on:
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
        branches:
            - 'release/**'

jobs:
    check_release_branch:
        name: No Commits
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
                  fetch-depth: 0

            - name: Fetch base branch
              run: |
                  git fetch origin ${{ github.event.pull_request.base.ref }}

            - name: Check base branch has no commits since merge base
              env:
                  BASE_BRANCH_HEAD_SHA: ${{ github.event.pull_request.base.sha }}
                  PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
              run: |
                  set -x
                  MERGE_BASE=$(git merge-base $PR_HEAD_SHA $BASE_BRANCH_HEAD_SHA)
                  echo $MERGE_BASE
                  echo $BASE_BRANCH_HEAD_SHA
                  if [ $MERGE_BASE != $BASE_BRANCH_HEAD_SHA ]; then
                    echo "Base branch has commits since merge base"
                    exit 1
                  fi

    check_pr_branch:
        name: Check PR branch
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Get branch name of the PR
              id: pr_branch_name
              run: |
                  pr_branch_name=$(git branch --show-current)
                  echo "result=$PR_BRANCH_NAME" >> $GITHUB_OUTPUT

            - name: Assert pull request is created from a RC branch
              env:
                  PR_BRANCH_NAME: ${{ steps.pr_branch_name.outputs.result }}
              run: |
                  set -x
                  if [ $PR_BRANCH_NAME != rc/* ]; then
                      echo "Pull request to release branch must come from RC branch"
                      exit 1
                  fi

            - name: Parse version
              id: version
              uses: ./.github/parse-version

            - name: Assert release version is not pre-release
              env:
                  RELEASE_VERSION: ${{ steps.version.outputs.releaseVersion }}
              run: |
                  set -x
                  echo $RELEASE_VERSION
                  if [ $RELEASE_VERSION = *-pre ]; then
                    echo "Release version cannot be pre-release"
                    exit 1
                  fi

            - name: Assert release version matches RC branch name
              env:
                  PR_BRANCH_NAME: ${{ steps.pr_branch_name.outputs.result }}
                  RELEASE_SHORT: ${{ steps.version.outputs.releaseShort }}
              run: |
                  set -x
                  echo $PR_BRANCH_NAME
                  echo $RELEASE_SHORT
                  if [ $PR_BRANCH_NAME != "rc/v$RELEASE_SHORT" ]; then
                      echo "Release version does not match RC branch"
                      exit 1
                  fi
